### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by qq5460168** [miaoermua/AdguardFilter#10]
## 遇到问题
||*.mobi^
为什么要把这个域名段 全部拦截 ？

## 来源

应用名称/网站地址: `Chrome & https:// `

设备: 安卓   叮咚买菜app  误杀 

- [] 网站(浏览器)
- [ ] 应用内(浏览器)
- [x ] 应用       叮咚买菜
- [ ] 监听网络
- [ ] 系统应用

**Comment by miaoermua** [comment]
已移除，是前群友留下的规则
