### ISSUE TITLE
mac登录状态不正常

### ISSUE THREAD

**Issue by encyclist** [miaoermua/AdguardFilter#9]
## 遇到问题
mac提示账户需要重新验证，且继续按钮点击无响应
## 来源
bad_apple.txt
应用名称/网站地址: 
放行`setup.fe2.apple-dns.net`和`gateway.fe.apple-dns.cn`后恢复
设备: 
MacOS
- [ ] 网站(浏览器)
- [ ] 应用内(浏览器)
- [x] 应用
- [ ] 监听网络

**Comment by miaoermua** [comment]
黑名单列表需要搭配白名单一起用才可以避免误杀，你可以把白名单也加上去看看还有没有问题。

黑名单列表: https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/bad_apple.txt

白名单列表: https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/whitelist.txt

**Comment by encyclist** [comment]
> 黑名单列表需要搭配白名单一起用才可以避免误杀，你可以把白名单也加上去看看还有没有问题。
> 
> 黑名单列表: https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/bad_apple.txt黑名单列表： https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/bad_apple.txt
> 
> 白名单列表: https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/whitelist.txt

一已经添加了，白名单里似乎没有这两个

**Comment by miaoermua** [comment]
> > 黑名单列表需要搭配白名单一起用才可以避免误杀，你可以把白名单也加上去看看还有没有问题。
> > 黑名单列表: [https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/bad_apple.txt黑名单列表：](https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/bad_apple.txt%E9%BB%91%E5%90%8D%E5%8D%95%E5%88%97%E8%A1%A8%EF%BC%9A) https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/bad_apple.txt
> > 白名单列表: https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/whitelist.txt
> 
> 一已经添加了，白名单里似乎没有这两个

Apple 大部分域名都是依靠 cname 层层套的，没有也很正常，可以测试一下还有没有问题

**Comment by miaoermua** [comment]
感觉怎么样了
